name: Deploy CloudFormation Template

on:
  push:
    branches:
      - main  # Or the branch you want to trigger deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  

    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --template-file lab-network.yaml \
          --stack-name my-cloudformation-stack \
          --capabilities CAPABILITY_NAMED_IAM
    - name: Deploy EC2 Stack
      run: |
        aws cloudformation deploy \
          --template-file lab-application2.yaml \
          --stack-name lab-app \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides NetworkStackName=my-cloudformation-stack